### ISSUE TITLE
Strange Scrolling in Kits page

### ISSUE THREAD

**Issue by lizane** [UnionDesign/yarn-sites#106]
When ordering a kit on http://staging.fleeceartist.flywheelsites.com/kits/ the page starts scrolling up and down ON ITS OWN each time you order a kit (for about 8 seconds). It would always end up on the Perl Grey- Betsy pattern with the Hand Dyed colour option table open. This does it on both Safari and Chrome.

**Comment by UnionDesign** [comment]
This was fixed a month ago. Please make sure you completely clear all of your caches in all of your browsers before doing any testing. You should clear your cache every time you start a new testing session.

**Comment by lizane** [comment]
when you add a kit to cart, this is the behaviour after clicking 'add to cart. still happening.

**Comment by lizane** [comment]
The weird scrolling is no longer happening (yey!)

Now when you first scroll into the Kits pages though, the colour panel for the Perl Grey-Betsy is showing up already opened, as well as the colour panel for the Classic Thrums further down the scroll.

The colour panel disappears/closes up after a few seconds for the Perl Grey- Betsy. The panel for the Classic Thrums stays for a bit longer.

This is not really a functioning issue, but it might be a small aesthetic issue.

![screen shot 2015-08-19 at 10 33 54 am](https://cloud.githubusercontent.com/assets/9930894/9357643/802b90a6-465e-11e5-9076-6ff5a5662db4.png)

**Comment by lizane** [comment]
The same thing is happening in Safari as it is in Chrome.

**Comment by UnionDesign** [comment]
Fixed
